language: php

php:
  - 5.5
  - 5.6
  - 7
  - 7.1
  - hhvm

matrix:
  include:
    # Add PHP 7 build to check codestyle only in PHP 7 build
    - php: 7
      env: CHECK_CODESTYLE=1
      before_script: ~
      script:
        - ./vendor/bin/php-cs-fixer fix --diff --dry-run
        - ./vendor/bin/phpcs --standard=PSR2 ./lib/ ./tests/

env:
  global:
    - DISPLAY=:99.0

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction

before_script:
  - sh -e /etc/init.d/xvfb start
  - wget -q -t 3 http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar
  - java -jar selenium-server-standalone-2.45.0.jar -log selenium.log &
  - until $(echo | nc localhost 4444); do sleep 1; echo waiting for selenium-server...; done

script:
  - ./vendor/bin/phpunit

after_script:
  - cat selenium.log
