language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  include:
    # Add build to run tests against Firefox inside Travis environment (other runs are agains HtmlUnit by default)
    - php: 7.0
      env: BROWSER_NAME="firefox"
      addons:
        firefox: "latest-esr"
        apt:
          packages:
            - oracle-java8-installer

    # Build with lowest possible dependencies
    - php: 7.0
      env: dependencies="--prefer-lowest"

    # Saucelabs builds
    - php: 7.0
      env: SAUCELABS=1 BROWSER_NAME="firefox" VERSION="47.0" PLATFORM="Windows 10"
      before_script: php -S localhost:8000 -t tests/functional/web/ &>>./logs/php-server.log &
      addons:
        sauce_connect: true
        jwt:
          secure: HPq5xFhosa1eSGnaRdJzeyEuaE0mhRlG1gf3G7+dKS0VniF30husSyrxZhbGCCKBGxmIySoAQzd43BCwL69EkUEVKDN87Cpid1Ce9KrSfU3cnN8XIb+4QINyy7x1a47RUAfaaOEx53TrW0ShalvjD+ZwDE8LrgagSox6KQ+nQLE=
    - php: 7.0
      env: SAUCELABS=1 BROWSER_NAME="firefox" VERSION="45.0" PLATFORM="Linux"
      before_script: php -S localhost:8000 -t tests/functional/web/ &>>./logs/php-server.log &
      addons:
        sauce_connect: true
        jwt:
          secure: HPq5xFhosa1eSGnaRdJzeyEuaE0mhRlG1gf3G7+dKS0VniF30husSyrxZhbGCCKBGxmIySoAQzd43BCwL69EkUEVKDN87Cpid1Ce9KrSfU3cnN8XIb+4QINyy7x1a47RUAfaaOEx53TrW0ShalvjD+ZwDE8LrgagSox6KQ+nQLE=
    - php: 7.0
      env: SAUCELABS=1 BROWSER_NAME="chrome" VERSION="latest" PLATFORM="Windows 10"
      before_script: php -S localhost:8000 -t tests/functional/web/ &>>./logs/php-server.log &
      addons:
        sauce_connect: true
        jwt:
          secure: HPq5xFhosa1eSGnaRdJzeyEuaE0mhRlG1gf3G7+dKS0VniF30husSyrxZhbGCCKBGxmIySoAQzd43BCwL69EkUEVKDN87Cpid1Ce9KrSfU3cnN8XIb+4QINyy7x1a47RUAfaaOEx53TrW0ShalvjD+ZwDE8LrgagSox6KQ+nQLE=

    # Add PHP 7 build to check codestyle only in PHP 7 build
    - php: 7.0
      env: CHECK_CODESTYLE=1
      before_script: ~
      script:
        - ./vendor/bin/php-cs-fixer fix --diff --dry-run
        - ./vendor/bin/phpcs --standard=PSR2 ./lib/ ./tests/
      after_script: ~
      after_success: ~

env:
  global:
    - DISPLAY=:99.0

cache:
  directories:
    - $HOME/.composer/cache
    - jar

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --no-interaction $dependencies

before_script:
  - sh -e /etc/init.d/xvfb start
  - if [ ! -f jar/selenium-server-standalone-3.1.0.jar ]; then wget -q -t 3 -P jar https://selenium-release.storage.googleapis.com/3.1/selenium-server-standalone-3.1.0.jar; fi
  - /usr/lib/jvm/java-8-oracle/bin/java -Dwebdriver.firefox.marionette=false -jar jar/selenium-server-standalone-3.1.0.jar -log ./logs/selenium.log &
  - until $(echo | nc localhost 4444); do sleep 1; echo waiting for selenium-server...; done
  - php -S localhost:8000 -t tests/functional/web/ &>>./logs/php-server.log &

script:
  - ./vendor/bin/phpunit --coverage-clover ./logs/coverage-clover.xml

after_script:
  - cat ./logs/selenium.log
  - cat ./logs/php-server.log

after_success:
  - travis_retry php vendor/bin/coveralls -v

addons:
  apt:
    packages:
      - oracle-java8-installer
